/*
 * AvaTax API Client Library
 *
 * (c) 2004-2018 Avalara, Inc.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 */

/// Type of certificate preview to download

global enum CertificatePreviewType
{

    /// Download a full printable PDF
    Pdf,

    /// Download a single page of the certificate in JPG format
    Jpeg,

}
