/*
 * AvaTax API Client Library
 *
 * (c) 2004-2018 Avalara, Inc.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 */

/// Comment Types

global enum CommentType
{

    /// Internal comments are those comments only intended to be for compliance users
    Internal,

    /// Customer comments are those comments that both compliance and the customer can read
    Customer,

}
