/*
 * AvaTax API Client Library
 *
 * (c) 2004-2018 Avalara, Inc.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 */

/// Types of jurisdiction referenced in a transaction

global enum JurisTypeId
{

    /// State
    STA,

    /// County
    CTY,

    /// City
    CIT,

    /// Special
    STJ,

    /// Country
    CNT,

}
