/*
 * AvaTax API Client Library
 *
 * (c) 2004-2018 Avalara, Inc.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 */

/// Type of file request

global enum PointOfSaleFileType
{

    /// File is in Javascript Object Notation format
    Json,

    /// File is in Comma Separated Values format
    Csv,

    /// File is in Extended Markup Language format
    Xml,

}
