/*
 * AvaTax API Client Library
 *
 * (c) 2004-2018 Avalara, Inc.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 */

/// 

global enum RateType
{

    /// 
    ReducedA,

    /// 
    ReducedB,

    /// 
    Food,

    /// 
    General,

    /// 
    IncreasedStandard,

    /// 
    LinenRental,

    /// 
    Medical,

    /// 
    Parking,

    /// 
    SuperReduced,

    /// 
    ReducedR,

    /// 
    Standard,

    /// 
    Zero,

}
