/*
 * AvaTax API Client Library
 *
 * (c) 2004-2018 Avalara, Inc.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 */

/// Different types of formats allowed for exporting a report

global enum ReportFormat
{

    /// The Comma Separated Values file format
    CSV,

    /// The Extensible Markup Language file format
    XML,

}
