global class AddressInfo
    {
        global String line1 { get; set; }

        global String line2 { get; set; }

        global String line3 { get; set; }

        global String city { get; set; }

        global String region { get; set; }

        global String country { get; set; }

        global String postalCode { get; set; }

        global Double latitude { get; set; }

        global Double longitude { get; set; }

    }