public enum AddressCategoryId
{
    /// Address refers to a storefront location
    Storefront,

    /// Address refers to a main office of this company
    MainOffice,

    /// Address refers to a warehouse or other non-public location
    Warehouse,

    /// Address refers to a location for a single salesperson
    Salesperson,

    /// Address is a type not reflected in the other lists
    Other
}