global class FundingESignMethodReturn
    {
        /// <summary>
        /// Method
        /// </summary>
        global String method { get; set; }

        /// <summary>
        /// JavaScriptReady
        /// </summary>
        global Boolean javaScriptReady { get; set; }

        /// <summary>
        /// The actual javascript to use to render this object
        /// </summary>
        global String javaScript { get; set; }

}