global enum MatchingTaxType
{
    /// Match medical excise type
    Excise,

    /// Match Lodging tax type
    Lodging,

    /// Match bottle tax type
    Bottle,

    /// Match all tax types
    All,

    /// Match both Sales and Use Tax only
    BothSalesAndUseTax,

    /// Match Consumer Use Tax only
    ConsumerUseTax,

    /// Match both Consumer Use and Seller's Use Tax types
    ConsumersUseAndSellersUseTax,

    /// Match both Consumer Use and Sales Tax types
    ConsumerUseAndSalesTax,

    /// Match Fee tax types only
    Fee,

    /// Match VAT Input Tax only
    VATInputTax,

    /// Match VAT Nonrecoverable Input Tax only
    VATNonrecoverableInputTax,

    /// Match VAT Output Tax only
    VATOutputTax,

    /// Match Rental tax types only
    Rental,

    /// Match Sales Tax only
    SalesTax,

    /// Match Seller's Use Tax only
    UseTax

}