global enum OutletTypeId
{
    /// File a single return per cycle for your entire business.
    None,

    /// You may file separate forms for each outlet; contact the tax authority for more details about location based reporting requirements.
    Schedule,

    /// You may file separate forms for each outlet; contact the tax authority for more details about location based reporting requirements.
    Duplicate,

    /// File a single return, but you must have a line item for each place of business.
    Consolidated

}