/*
 * AvaTax API Client Library
 *
 * (c) 2004-2018 Avalara, Inc.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 */

/* The output DocumentType for a report */

global enum ReportDocType
{

    // Output all ConsumerUse tax transactions in the report
    ConsumerUse,

    // Output all Sales tax transactions in the report
    Sales,

}
