global enum SecurityRoleId
    {
        NoAccess,
        
        SiteAdmin,

        AccountOperator,

        AccountAdmin,

        AccountUser,

        SystemAdmin,

        Registrar,

        CSPTester,

        CSPAdmin,

        SystemOperator,

        TechnicalSupportUser,

        TechnicalSupportAdmin,

        TreasuryUser,

        TreasuryAdmin,

        ComplianceUser,

        ComplianceAdmin,

        ProStoresOperator,

        CompanyUser,

        CompanyAdmin,

        ComplianceTempUser,

        ComplianceRootUser,

        ComplianceOperator,

        SSTAdmin
    }