global enum TaxType
{
    /// Match Lodging tax type
    Lodging,

    /// Match bottle tax type
    Bottle,

    /// EWaste tax type
    EWaste,

    /// Consumer Use Tax
    ConsumerUse,

    /// Medical Excise Tax
    Excise,

    /// Fee - PIFs (global Improvement Fees) and RSFs (Retail Sales Fees)
    Fee,

    /// VAT/GST Input tax
    Input,

    /// VAT/GST Nonrecoverable Input tax
    Nonrecoverable,

    /// VAT/GST Output tax
    Output,

    /// Rental Tax
    Rental,

    /// Sales tax
    Sales,

    /// Use tax
    Use

}