/*
 * AvaTax API Client Library
 *
 * (c) 2004-2018 Avalara, Inc.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 */

/* Filing worksheet Type */

global enum WorksheetTypeId
{

    // The original filing for a period
    Original,

    // Represents an amended filing for a period
    Amended,

    // Represents a test filing
    Test,

}
